/*
 * This file is generated by jOOQ.
 */
package com.example.schema;


import com.example.schema.tables.FlywaySchemaHistory;
import com.example.schema.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>USERS</code>.
     */
    public static final Users USERS = com.example.schema.tables.Users.USERS;

    /**
     * The table <code>flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.example.schema.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;
}
